import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "@/app/page.module.css";
import UsersDialogComponent from "@/components/users-dialog/users-dialog";
import UsersListComponent from "@/components/users-list/users-list";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.page}>
          <nav className={styles.pageNav}>
            <div className={styles.navTitle}>
              <h1>React</h1>
              <div className={styles.navTitleLine}></div>
            </div>
            <div className={styles.navTitle}>
              <div className={styles.navTitleLine}></div>
              <h1>Exercise</h1>
            </div>
            <Link href="/sign-up">Sign up</Link>
            <UsersDialogComponent>
              <UsersListComponent />
            </UsersDialogComponent>
          </nav>
          <main className={styles.pageMain}>{children}</main>
        </div>
      </body>
    </html>
  );
}
